// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration_addDraftAndTrash_inMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_addDraftAndTrash_inMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "202106081659083_migration_addDraftAndTrash_inMessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
